### ISSUE TITLE
Timetable for dropping Scala 2.10 support?

### ISSUE THREAD

**Issue by SethTisue** [typesafehub/genjavadoc#118]
This came up on #108. Since genjavadoc involves scalac internals, supporting so many different Scala versions takes some effort. 2.10 has been EOL for a long time; is it time to drop support?

**Comment by SethTisue** [comment]
my own sense is that 2.10 users will be fine using existing releases of genjavadoc and we don't need to keep releasing new versions for them. (but, others are closer to this project and its users than I am.)

**Comment by patriknw** [comment]
it can be dropped from Akka's perspective

**Comment by 2m** [comment]
Support dropped with https://github.com/typesafehub/genjavadoc/pull/108

**Comment by patriknw** [comment]
@SethTisue I have added scala-team as Admin here
