### ISSUE TITLE
Link warnings

### ISSUE THREAD

**Issue by patriknw** [typesafehub/genjavadoc#29]
I think the scaladoc links doesn't include full package name.

    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/SupervisorStrategy$.java:42: warning - Tag @link: reference not found: Decider
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/SupervisorStrategy.java:80: warning - Tag @link: reference not found: Decider
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/IO.java:451: warning - Tag @link: reference not found: akka.actor.IO.EOF
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/dsl/Inbox.java:78: warning - Tag @link: reference not found: akka.actor.dsl.Inbox!.Inbox!.receive
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/dsl/Inbox.java:78: warning - Tag @link: reference not found: akka.actor.dsl.Inbox!.Inbox!.select
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/io/Tcp.java:493: warning - Tag @link: reference not found: Abort
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/io/Tcp.java:498: warning - Tag @link: reference not found: ConfirmedClose
    [warn] /Users/patrik/dev/akka/akka-actor/target/java/akka/actor/ActorSystem.java:191: warning - Tag @link: reference not found: ActorSystem.eventStream

**Comment by rkuhn** [comment]
These are cases where the original code is in error: there are no Java types to link to.
