### ISSUE TITLE
'File Not Found Exception' 

### ISSUE THREAD

**Issue by phil-rice** [typesafehub/genjavadoc#32]
I'm creating a scala project  https://github.com/phil-rice/cddcore. There is a branch called JavadocCompilerException that holds the code that I'm raising the issue over.

When I follow the instructions given in  http://www.scala-sbt.org/release/docs/Howto/scaladoc.html, I get an error message which is loads of source code followed by:
[error] uncaught exception during compilation: java.io.FileNotFoundException
[error] C:\Users\Phil\git\cddcore\constraint\target\java\<empty>\LatestLens.java (The filename, directory name or volume label syntax is incorrect)
[error] two errors found
[error] (constraint/compile:compile) Compilation failed
[error] Total time: 5 s, completed 10-Nov-2013 20:23:06

If this was a normal scala thing, I'd be downloading the source code, putting in breakpoints and looking at stuff. But I've looked at the compiler code before, and it's very scary!

I have here a zip of the offending code in case you have problems with the github:: https://www.dropbox.com/s/rsaxt6u4t3lj2ey/cddcore.zip
SBT in the root directory should work. (If you remove the javadocsettings from project/build.scala everything works nicely).

For your information:
I am using macros in this code, but the LatestLens isn't part of the macro code.

**Comment by rkuhn** [comment]
Thanks for the report, even though it took me quite a while to get around to it. The error is quite simple, the root package needs special care.
