### ISSUE TITLE
NPE for trait in object

### ISSUE THREAD

**Issue by patriknw** [typesafehub/genjavadoc#34]
ReliableProxy.DebugLogging trait in akka-contrib cause NPE:

    [error] java.lang.NullPointerException
    [error]     at com.sun.tools.javadoc.ClassDocImpl.getFlags(ClassDocImpl.java:125)
    [error]     at com.sun.tools.javadoc.ClassDocImpl.isAnnotationType(ClassDocImpl.java:136)
    [error]     at com.sun.tools.javadoc.JavadocMemberEnter.isAnnotationTypeElement(JavadocMemberEnter.java:90)
    [error]     at com.sun.tools.javadoc.JavadocMemberEnter.visitMethodDef(JavadocMemberEnter.java:72)
    [error]     at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:653)
    [error]     at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:400)
    [error]     at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:412)
    [error]     at com.sun.tools.javac.comp.MemberEnter.finishClass(MemberEnter.java:422)
    [error]     at com.sun.tools.javac.comp.MemberEnter.finish(MemberEnter.java:1007)
    [error]     at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:974)
    [error]     at com.sun.tools.javac.code.Symbol.complete(Symbol.java:400)
    [error]     at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:782)
    [error]     at com.sun.tools.javac.comp.Enter.complete(Enter.java:481)
    [error]     at com.sun.tools.javac.comp.Enter.main(Enter.java:459)
    [error]     at com.sun.tools.javadoc.JavadocEnter.main(JavadocEnter.java:71)
    [error]     at com.sun.tools.javadoc.JavadocTool.getRootDocImpl(JavadocTool.java:180)
    [error]     at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:364)
    [error]     at com.sun.tools.javadoc.Start.begin(Start.java:162)
    [error]     at com.sun.tools.javadoc.Main.execute(Main.java:59)
    [error]     at com.sun.tools.javadoc.Main.main(Main.java:49)

The workaround can be seen here: https://github.com/akka/akka/pull/1947

**Comment by rkuhn** [comment]
This is not a bug in genjavadoc, it is a bug in javadoc.
