### ISSUE TITLE
Shorten links

### ISSUE THREAD

**Issue by patriknw** [typesafehub/genjavadoc#53]
Is it possible to automatically shorten the links, i.e. not include all the types? Links like this are rather insane: `start(java.lang.String, scala.Option<akka.actor.Props>, scala.Option<java.lang.String>, boolean, scala.PartialFunction<java.lang.Object, scala.Tuple2<java.lang.String, java.lang.Object>>, scala.Function1<java.lang.Object, java.lang.String>, akka.cluster.sharding.ShardCoordinator.ShardAllocationStrategy)`

**Comment by rkuhn** [comment]
This would require managing imports which is currently out of scope. But it would be an interesting enhancement.

**Comment by patriknw** [comment]
I mean the display of the links, i.e. the above example would display as **start**.

**Comment by rkuhn** [comment]
WDYM? can you give an example? genjavadoc does not generate links, that is done by javadoc unless I misunderstand you.

**Comment by patriknw** [comment]
genjavadoc generates `@link` tags, I guess, and there is a syntax for the display text. I think it is like this:

    {@link akka.actor.Actor#supervisorStrategy() supervisorStrategy}

**Comment by rkuhn** [comment]
Well, genjavadoc does not generate the link contents, that is done by you: just add the shortened version just as you would, it also benefits the ScalaDoc.

**Comment by patriknw** [comment]
Ok, perhaps I was annoyed at that the JavaDoc version got much longer than ScalaDoc. Closing
