### ISSUE TITLE
Travis broken for Scala 2.11.7

### ISSUE THREAD

**Issue by jodersky** [typesafehub/genjavadoc#79]
Take a look at https://travis-ci.org/typesafehub/genjavadoc/builds/121833192. Travis fails only for the Scala 2.11.7 on Java 8 configuration:

```
sbt.InvalidScalaInstance: Scala instance doesn't exist or is invalid: 
    version 2.11.7, library jar: /home/travis/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar, compiler jar: /home/travis/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.7.jar
```

The given config works on my local machine. Could travis have a corrupt cache?

**Comment by jodersky** [comment]
Everything works on my machine and, according to the error message, it really looks like it is an issue with travis' cache.
@2m, could you take a look at it? thanks

**Comment by 2m** [comment]
You were right. Fixed by cleaning Travis CI cache by running `travis cache --delete`.
