### ISSUE TITLE
Static forwarders are not filtered for java keywords

### ISSUE THREAD

**Issue by 2m** [typesafehub/genjavadoc#81]
It looks like after https://github.com/typesafehub/genjavadoc/commit/d5123a3a8f8b658610b0c97b829e2098050e92e1 static forwarders are not filtered for java keywords. This makes JavaDoc generation fail for Akka with the master version of genjavadoc.

For example with the latest genjavadoc [AbstractFSM](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/AbstractFSM.scala) class has a `goto` method added to the generated java code from `FSM` which makes javadoc stop with an error.

From my investigation it looks like filtering for java keywords is done in [`PreFilter`](https://github.com/typesafehub/genjavadoc/blob/master/plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala#L85) which is only applied to [`nestedClasses` and `nestedStaticClasses`](https://github.com/typesafehub/genjavadoc/blob/master/plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala#L131-L132) and not to [`staticMethods`](https://github.com/typesafehub/genjavadoc/blob/master/plugin/src/main/scala/com/typesafe/genjavadoc/Output.scala#L121) which was added in the above mentioned commit.

@mengxr @jodersky do you think this is accurate and the fix would be to apply filter for java keywords to `staticMethods`?

**Comment by mengxr** [comment]
I don't know much about the internals, but it seems that `inheritedMethods` doesn't filter Java keywords either.

**Comment by jodersky** [comment]
I can have a look at this tomorrow

**Comment by jodersky** [comment]
Submitted a quick fix
